name: charts_example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  get:
  fl_chart: ^0.12.0
  intl: ^0.16.1
  graphx:
    git:
      url: git@github.com:roipeker/graphx.git
      ref: 8be98ad0a56338100e9cfc75394798331bc2d914

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
