name: charts_example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  get:
  fl_chart: ^0.12.0
  intl: ^0.16.1
  graphx: 
    git: https://github.com/roipeker/graphx.git
    # version: 1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
